databases:
  - name: gwamajedb
    plan: free
    databaseName: gwamajedb
    user: bheki

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn digwamaje.asgi:application -k uvicorn.workers.UvicornWorker"
    staticPublishPath: staticfiles
    routes:
      - type: rewrite
        source: /media/(.*)
        destination: /media/\1
      - type: rewrite
        source: /(.*)
        destination: /static\1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gwamajedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  